name: CICD

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout Metabase Repo
        uses: actions/checkout@v2
        with:
          repository: metabase/metabase
          ref: v1.43.2
      - name: Checkout Driver Repo
        uses: actions/checkout@v2
        with:
          path: modules/drivers/druid
      - name: Prepare JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '11'
      - name: Install Clojure CLI
        run: |
          curl -O https://download.clojure.org/install/linux-install-1.10.3.1029.sh &&
          sudo bash ./linux-install-1.10.3.1029.sh
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '14'
          cache: 'yarn'
      - name: Get M2 cache
        uses: actions/cache@v2
        with:
          path: |
            ~/.m2
            ~/.gitlibs
          key: ${{ runner.os }}-druid-${{ hashFiles('**/deps.edn') }}
      - name: Build Druid driver
        run: |
          bin/build-driver.sh druid
      - name: Archive driver JAR
        uses: actions/upload-artifact@v2
        with:
          name: druid.metabase-driver.jar
          path: resources/modules/druid.metabase-driver.jar
      - name: Publish archives and packages
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            resources/modules/druid.metabase-driver.jar
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
